[package]
name = "api"
version = "0.1.0"
authors = ["Thomas Eckert <thomas.james.eckert@gmail.com>"]
edition = "2018"

[dependencies]
rocket = { version = "0.5.0-rc.1", features = ["json"] }
reqwest = "0.11.3"
serde = "*"
